language: node_js
node_js:
- '8'
cache: yarn
sudo: false
dist: trusty
script: yarn build
deploy:
  provider: s3
  bucket: "kuis.ski"
  local_dir: build
  skip_cleanup: true
  acl: public_read
  access_key_id: "AKIAJ77FHWYH56ABOBHQ"
  secret_access_key:
    secure: i0+3v6EID5N1L/kaYj6fLX7AAWhCyTVN74etmgIKqej9pfQ//C7FCjfg3bnmM40EkWy/M3xwDzYBF6Y5NL6gUXVMjXYHO7WyUp46ppxsymdXht5w/IUhe2FpqIlQFLRPcHcuZEYIerbkWdIO49lgnBptoZgxeHhxo2t1zUjqGR2Lexp0m6B+WN5qWiCMFPDmtDRUAk8GcXTYs2KedJCX4hF/TdaMWV8JSWBgkjggvgVcrp5mtddprF5h/pDLlEUYEQvXVl+DwGP+3HghRHzaFVD4/z2muKyHlR2myKgmRGhg1sQ2icW6LeU5YEY6T4bF5XJ08B4dcHKAFrRvbkdI4zGJsNMuwUsdgC2D1TMzexRnSTR88vZffT56pDraKUfSDqLakoXPQHhixJZt0nL2oUL+JYEwmd+7vPRjommXVs8e2keOpZu4WKlgjGTc+8E6nKQnjqFoJCPmw9jy5qdMhGNbMLur8FfvtscpzfcJjnAc0PwiXhtW2spe/rrUy/1i+jsopO+4erbffmKSU3GCyFRGEk0jkO9D7P+uKV1busmladXNt8QixmSjam8KV6k3wYXW2XKk7suFR+mCZT1EYA0KfuKnfcjncQxtRkzaYpaFg655vwI0w7hNysRGMkc6oXwvtof10zdwhWd5jOJd9uIgEnmwudiJi2LssxNU3LA=
